const country = {
  currency: 'PEN',
  prices: {
    combo: '44.90',
    monthly: '25.90',
    yearly: '259.90'
  }
}

const languages = {
  english: {
    loginButton: 'LOG IN',
    signupButton: 'SIGN UP NOW',
    signupOnlyMonthly: 'Sign up only to Disney+ monthly',
    signupOnlyYearly: 'Sign up only to Disney+ yearly',
    offerComboPlusButton: 'GET COMBO+ OFFER',
    heroTitle: 'Enjoy the greatest stories, all in one place.',
    planListTitle: 'Choose your plan',
    planListFooter: '*The price may vary if billed through other currencies, platforms or payment methods. Third party charges may apply.',
    planComboTitle: 'GET STAR+ & DISNEY+',
    planComboCurrency: `${country.currency} ${country.prices.combo}/month*`,
    planComboDescription: 'Save and get the two services together, with this unique offer. Enjoy now Disney+ and Star+ for a special price.',
    planComboButtonText: 'SIGN UP TO COMBO+',
    planMonthlyTitle: 'DISNEY+ MONTHLY',
    planMonthlyCurrency: `${country.currency} ${country.prices.monthly}/month*`,
    planMonthlyDescription: 'Purchase the Disney+ monthly plan and enjoy the latest releases that come from the cinema, originals and classics.',
    planMonthlyButtonText: 'SIGN UP',
    planYearlyTitle: 'DISNEY+ YEARLY',
    planYearlyCurrency: `${country.currency} ${country.prices.yearly}/year*`,
    planYearlyDescription: 'A full year of series and movies from Disney, Pixar, Marvel, Star Wars and National Geographic at a unique price.',
    planYearlyButtonText: 'SIGN UP',
    multidevicesInfoTitle: 'Watch the way you want',
    multidevicesInfoDescription: 'Enjoy the big screen experience on your TV, or watch on your tablet, laptop, phone and more. You can watch an ever-growing selection of titles in 4K. Plus, you can stream on 4 screens at once, so everyone’s happy.',
    exclusiveTitle: 'Exclusive Disney+ Originals',
    exclusiveDescription: 'Watch never-before-seen movies, series, shorts and more from the world’s greatest storytellers - only available on Disney+',
    downloadSectionTitle: 'Download any series or movie',
    downloadSectionDescription: 'Download whatever you want and watch whenever you want. Your favorites will always stay with you, even if your Wi-Fi won’t.',
    devicesTitle: 'Available on your favourite devices',
    devicesComputerTitle: 'Computer',
    devicesComputerList: ['Chrome OS', 'MacOS', 'Windows PC'],
    devicesTvTitle: 'TV',
    devicesTvList: ['Amazon Fire TV', 'Android TV', 'Apple TV', 'Chromecast', 'LG TV', 'Samsung'],
    devicesGameConsolesTitle: 'Game Consoles',
    devicesGameConsolesList: ['PS4', 'PS5', 'Xbox One', 'Xbox Series X', 'Xbox Series S'],
    devicesMobileTabletTitle: 'Mobile & Tablet',
    devicesMobileTabletList: ['Amazon Fire Tablets', 'Android Phones & Tablets', 'iPhone & iPad'],
    FAQTitle: 'Frequently Asked Questions',
    FAQ1: 'What is Disney+?',
    FAQ1AnswerTitle: 'With Disney+, you get:',
    FAQ1AnswerList: [
      'A premium ad-free experience.',
      'The greatest stories of Disney, Pixar, Marvel, Star Wars, and National Geographic, all in one place.',
      'GroupWatch, a way to watch Disney+ together, even when you’re apart.',
      'Unlimited downloads on up to 10 devices.',
      'Over 100 titles in 4K UHD and HDR.',
      'Up to 4 current streams.',
      'IMAX Enhanced. Available with certain Marvel titles and accessible on all devices where Disney+ is supported.'
    ],
    FAQ2: 'Do you already have a Disney+ or Star+ subscription but want Combo+?',
    FAQ2AnswerTitle: 'With Combo+:',
    FAQ2AnswerList: [
      'We will discount the value of your existing subscription to the Combo+ deal. (Yes, for the annual plan as well!)',
      'If you have a monthly subscription, your monthly bill will be reduced to the Combo+ price.',
      'If you have an annual subscription, we will divide your annual price into 12 equal parts and discount the monthly price to the Combo+ monthly payment.',
      'A detailed email with all of the payment charges and deductions will be sent to your inbox as soon as you confirm your Combo+ payment method.',
      'Remember you can cancel at any moment.'
    ],
    FAQ2AnswerFootnote: 'The Combo+ subscription is only offering a monthly plan at this moment.',
    FAQ3: 'What payment methods can I use?',
    FAQ3Answer: 'You can pay by credit card, debit card and through third parties.'
  },
  spanish: {
    loginButton: 'INICIAR SESIÓN',
    signupButton: 'SUSCRÍBETE AHORA',
    signupOnlyMonthly: 'Suscribirme solo a Disney+ mensual',
    signupOnlyYearly: 'Suscribirme solo a Disney+ anual',
    offerComboPlusButton: 'CONTRATÁ OFERTA COMBO+',
    heroTitle: 'Tus historias favoritas, todas en un mismo lugar.',
    planListTitle: 'Elige tu plan',
    planListFooter: '* El precio podría variar en caso de que el pago se realice en otras monedas, plataformas o medios de pago. Podrían aplicar cargos de terceros.',
    planComboTitle: 'CONTRATA DISNEY+ Y STAR+',
    planComboCurrency: `${country.currency} ${country.prices.combo}/mes*`,
    planComboDescription: 'Ahorra contratando los dos servicios juntos con esta oferta única. Disfruta Disney+ y Star+ por un precio único.',
    planComboButtonText: 'SUSCRÍBETE A COMBO+',
    planMonthlyTitle: 'DISNEY+ MENSUAL',
    planMonthlyCurrency: `${country.currency} ${country.prices.monthly}/mes*`,
    planMonthlyDescription: 'Contrata el plan mensual de Disney+ y disfruta los últimos estrenos del cine, originales y clásicos inolvidables.',
    planMonthlyButtonText: 'SUSCRÍBETE AHORA',
    planYearlyTitle: 'DISNEY+ ANUAL',
    planYearlyCurrency: `${country.currency} ${country.prices.yearly}/año*`,
    planYearlyDescription: 'Por un precio único, todo un año de películas y series de Disney, Pixar, Marvel, Star Wars y National Geographic.',
    planYearlyButtonText: 'SUSCRÍBETE AHORA',
    multidevicesInfoTitle: 'Cuando quieras, donde quieras',
    multidevicesInfoDescription: 'Disfrútalo en tu pantalla favorita, ya sea tu TV, tableta, computadora, teléfono y otros. Vive una experiencia única con una amplia selección de títulos en 4K. Además, puedes ver en cuatro pantallas en simultáneo para que nadie se quede afuera.',
    exclusiveTitle: 'Originales de Disney+ exclusivos',
    exclusiveDescription: 'Disfruta de películas, series y documentales nunca antes vistos. Solo en Disney+.',
    downloadSectionTitle: 'Descarga series y películas',
    downloadSectionDescription: 'Descargas ilimitadas para ver lo que quieras, cuando quieras. Lleva tus historias favoritas siempre contigo, incluso sin conexión.',
    devicesTitle: 'Disponible en tus dispositivos favoritos',
    devicesComputerTitle: 'Computadoras',
    devicesComputerList: ['Chrome OS', 'MacOS', 'Windows PC'],
    devicesTvTitle: 'TV',
    devicesTvList: ['Amazon Fire TV', 'Android TV', 'Apple TV', 'Chromecast', 'LG TV', 'Samsung'],
    devicesGameConsolesTitle: 'Consolas',
    devicesGameConsolesList: ['PS4', 'PS5', 'Xbox One', 'Xbox Series X', 'Xbox Series S'],
    devicesMobileTabletTitle: 'Celulares y tabletas',
    devicesMobileTabletList: ['Tabletas Amazon Fire', 'Celulares y tabletas Android', 'iPhone y iPad'],
    FAQTitle: 'Preguntas frecuentes',
    FAQ1: '¿Qué incluye Disney+?',
    FAQ1AnswerTitle: 'Beneficios de la suscripción a Disney+:',
    FAQ1AnswerList: [
      'Experiencia prémium sin cortes comerciales.',
      'Las mejores historias de Disney, Pixar, Marvel, Star Wars y National Geographic, todo en un mismo lugar.',
      'Groupwatch: comparte tus historias favoritas, aunque estés lejos.',
      'Descargas ilimitadas hasta en diez dispositivos compatibles.',
      'Más de 100 títulos en 4K UHD y HDR.',
      'Hasta cuatro pantallas a la vez: ¡disfrutan todos!',
      'IMAX Enhanced: disponible en algunos títulos de Marvel y en todos los dispositivos compatibles con Disney+.'
    ],
    FAQ2: '¿Ya tienes Disney+ o Star+ y quieres Combo+?',
    FAQ2AnswerTitle: 'Con Combo+:',
    FAQ2AnswerList: [
      'Descontaremos el valor de tu suscripción actual del precio de Combo+. (¡Sí, para el plan anual también!).',
      'Si tienes una suscripción mensual, el valor que pagas mensualmente se descontará del precio final de Combo+.',
      'Si tienes una suscripción anual, dividiremos el precio que pagaste en 12 partes iguales y descontaremos ese precio mensualmente del precio final de Combo+.',
      'Te llegará un correo electrónico con el detalle de los cargos apenas confirmes el pago.',
      'Recuerda que puedes cancelar en cualquier momento.'
    ],
    FAQ2AnswerFootnote: 'La suscripción a Combo+ es únicamente mensual, por el momento.',
    FAQ3: '¿Qué métodos de pago puedo usar?',
    FAQ3Answer: 'Puedes pagar con tarjeta de crédito, débito y a través de terceros.'
  }
}

export { languages }
